
server:
  port: 9001
  
spring:
  application:
    name: BootSecurity
  thymeleaf:
    cache: false # 请在线上环境打开cache
    prefix: classpath:/templates/
    mode: LEGACYHTML5  # HTML5
    encoding: UTF-8
    content-type: text/html 

#security:
#  basic:
#    enabled: false #默认开启   false表示关闭权限校验 
#  user:
#    name: admin
#    password: admin
#  sessions: stateless # 不创建和使用 session
#  ignored:
#  - user/login
#  - user/register


token: 
  header: token
  secret: secret
  expiration: 10800
  
  # JWT 604800  
jwt: 
  header: Authorization  
  secret: mySecret  
  expiration: 10  
  tokenHead: Bearer  
  route:
    authentication:
      path: auth/login  
      refresh: auth/refresh  
      register: auth/register